# permissions for end users to edit networkaddressbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkaddressbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-provisioner
    app.kubernetes.io/part-of: cluster-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: networkaddressbinding-editor-role
rules:
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings/status
  verbs:
  - get
