---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - tcproutes
  - tlsroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - tcproutes/status
  - tlsroutes/status
  verbs:
  - get
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vclusters/status
  verbs:
  - get
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbindings/status
  verbs:
  - get
