---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - cloudclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddressbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.seda.club
  resources:
  - networkaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproute
  - tcproute
  - tlsroute
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproute/status
  - tcproute/status
  - tlsroute/status
  verbs:
  - get
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - Cluster
  - VCluster
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - Cluster/status
  - VCluster/status
  verbs:
  - get
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbinding
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - tunnelbinding/status
  verbs:
  - get
